Resources:
  AuthorizerPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: cognito-api-gateway
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      UserPoolId: !Ref AuthorizerUserPool