Resources:
  Authorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties:
      ApiId: !Ref AuthorizerApi
      AuthorizerType: JWT
      IdentitySource:
        - "$request.header.Authorization"
      JwtConfiguration:
        Audience:
          - !Ref AuthorizerPoolClient
        Issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${AuthorizerUserPool}"
      Name: CognitoJwtAuthorizer
