Resources:
  AuthorizerApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref AuthorizerApi
      IntegrationMethod: GET
      IntegrationType: HTTP_PROXY
      IntegrationUri: https://www.facebook.com
      PayloadFormatVersion: "1.0"